steps:
  # 1. Build Docker image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/simple-ml-api:$SHORT_SHA", "."]

  # 2. Push image in Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/simple-ml-api:$SHORT_SHA"]

  # 3. Deploy pe Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "ml-model-service"
      - "--image"
      - "gcr.io/$PROJECT_ID/simple-ml-api:$SHORT_SHA"
      - "--region"
      - "europe-north2"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--port"
      - "8000"

# final image
images:
  - "gcr.io/$PROJECT_ID/simple-ml-api:$SHORT_SHA"
